// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToServer(arg1) {
  return window['go']['app']['App']['ConnectToServer'](arg1);
}

export function CreateProtoPath(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateProtoPath'](arg1, arg2, arg3);
}

export function CreateServerProfile(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['CreateServerProfile'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteProtoDefinition(arg1) {
  return window['go']['app']['App']['DeleteProtoDefinition'](arg1);
}

export function DeleteServerProfile(arg1) {
  return window['go']['app']['App']['DeleteServerProfile'](arg1);
}

export function DisconnectFromServer(arg1) {
  return window['go']['app']['App']['DisconnectFromServer'](arg1);
}

export function GetServerProfile(arg1) {
  return window['go']['app']['App']['GetServerProfile'](arg1);
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function ImportProtoFilesFromFolder() {
  return window['go']['app']['App']['ImportProtoFilesFromFolder']();
}

export function IsServerConnected(arg1) {
  return window['go']['app']['App']['IsServerConnected'](arg1);
}

export function ListProtoDefinitionsByProfile(arg1) {
  return window['go']['app']['App']['ListProtoDefinitionsByProfile'](arg1);
}

export function ListServerProfiles() {
  return window['go']['app']['App']['ListServerProfiles']();
}

export function SaveProtoDefinition(arg1) {
  return window['go']['app']['App']['SaveProtoDefinition'](arg1);
}

export function ScanAndParseProtoPath(arg1, arg2, arg3) {
  return window['go']['app']['App']['ScanAndParseProtoPath'](arg1, arg2, arg3);
}

export function SelectProtoFolder() {
  return window['go']['app']['App']['SelectProtoFolder']();
}

export function Shutdown(arg1) {
  return window['go']['app']['App']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}

export function UpdateServerProfile(arg1) {
  return window['go']['app']['App']['UpdateServerProfile'](arg1);
}
