// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToServer(arg1) {
  return window['go']['app']['App']['ConnectToServer'](arg1);
}

export function CreateServerProfile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['CreateServerProfile'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteServerProfile(arg1) {
  return window['go']['app']['App']['DeleteServerProfile'](arg1);
}

export function DisconnectFromServer(arg1) {
  return window['go']['app']['App']['DisconnectFromServer'](arg1);
}

export function GetServerProfile(arg1) {
  return window['go']['app']['App']['GetServerProfile'](arg1);
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function IsServerConnected(arg1) {
  return window['go']['app']['App']['IsServerConnected'](arg1);
}

export function ListServerProfiles() {
  return window['go']['app']['App']['ListServerProfiles']();
}

export function Shutdown(arg1) {
  return window['go']['app']['App']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}

export function UpdateServerProfile(arg1) {
  return window['go']['app']['App']['UpdateServerProfile'](arg1);
}
