// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {app} from '../models';
import {proto} from '../models';
import {context} from '../models';

export function ConnectToServer(arg1:string):Promise<void>;

export function CreateServerProfile(arg1:string,arg2:string,arg3:number,arg4:boolean,arg5:any):Promise<models.ServerProfile>;

export function DeleteProtoDefinition(arg1:string):Promise<void>;

export function DeleteServerProfile(arg1:string):Promise<void>;

export function DisconnectFromServer(arg1:string):Promise<void>;

export function GetServerProfile(arg1:string):Promise<models.ServerProfile>;

export function Greet(arg1:string):Promise<string>;

export function ImportProtoFilesFromFolder():Promise<Array<app.ProtoFileImport>>;

export function IsServerConnected(arg1:string):Promise<boolean>;

export function ListProtoDefinitionsByProfile(arg1:string):Promise<Array<proto.ProtoDefinition>>;

export function ListServerProfiles():Promise<Array<models.ServerProfile>>;

export function SaveProtoDefinition(arg1:proto.ProtoDefinition):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateServerProfile(arg1:models.ServerProfile):Promise<void>;
