// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function CreateCollection(arg1) {
  return window['go']['main']['App']['CreateCollection'](arg1);
}

export function CreateCollectionRequest(arg1) {
  return window['go']['main']['App']['CreateCollectionRequest'](arg1);
}

export function CreateHistoryItem(arg1) {
  return window['go']['main']['App']['CreateHistoryItem'](arg1);
}

export function CreateServerProfile(arg1) {
  return window['go']['main']['App']['CreateServerProfile'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteCollectionRequest(arg1) {
  return window['go']['main']['App']['DeleteCollectionRequest'](arg1);
}

export function DeleteHistoryItem(arg1) {
  return window['go']['main']['App']['DeleteHistoryItem'](arg1);
}

export function DeleteServerProfile(arg1) {
  return window['go']['main']['App']['DeleteServerProfile'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function ExportWorkspace() {
  return window['go']['main']['App']['ExportWorkspace']();
}

export function ImportWorkspace() {
  return window['go']['main']['App']['ImportWorkspace']();
}

export function Invoke(arg1) {
  return window['go']['main']['App']['Invoke'](arg1);
}

export function ListCollections() {
  return window['go']['main']['App']['ListCollections']();
}

export function ListHistoryItems(arg1) {
  return window['go']['main']['App']['ListHistoryItems'](arg1);
}

export function ListServerProfiles() {
  return window['go']['main']['App']['ListServerProfiles']();
}

export function ListServices() {
  return window['go']['main']['App']['ListServices']();
}

export function PickProtoFiles() {
  return window['go']['main']['App']['PickProtoFiles']();
}

export function PickProtoFolder() {
  return window['go']['main']['App']['PickProtoFolder']();
}

export function UpdateCollection(arg1, arg2) {
  return window['go']['main']['App']['UpdateCollection'](arg1, arg2);
}

export function UpdateCollectionRequest(arg1, arg2) {
  return window['go']['main']['App']['UpdateCollectionRequest'](arg1, arg2);
}

export function UpdateServerProfile(arg1, arg2) {
  return window['go']['main']['App']['UpdateServerProfile'](arg1, arg2);
}

export function ValidateProtoSources(arg1) {
  return window['go']['main']['App']['ValidateProtoSources'](arg1);
}
