// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearHistory():Promise<void>;

export function Connect(arg1:main.ConnectRequest):Promise<main.ConnectResponse>;

export function CreateCollection(arg1:main.SaveCollectionRequest):Promise<main.Collection>;

export function CreateCollectionRequest(arg1:main.SaveCollectionRequestItemRequest):Promise<main.CollectionRequest>;

export function CreateHistoryItem(arg1:main.SaveHistoryItemRequest):Promise<main.HistoryItem>;

export function CreateServerProfile(arg1:main.SaveServerProfileRequest):Promise<main.ServerProfile>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteCollectionRequest(arg1:string):Promise<void>;

export function DeleteHistoryItem(arg1:string):Promise<void>;

export function DeleteServerProfile(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function ExportWorkspace():Promise<main.WorkspaceTransferResult>;

export function ImportWorkspace():Promise<main.WorkspaceTransferResult>;

export function Invoke(arg1:main.InvokeRequest):Promise<main.InvokeResponse>;

export function ListCollections():Promise<Array<main.Collection>>;

export function ListHistoryItems(arg1:number):Promise<Array<main.HistoryItem>>;

export function ListServerProfiles():Promise<Array<main.ServerProfile>>;

export function ListServices():Promise<main.ListServicesResponse>;

export function PickProtoFiles():Promise<main.PickProtoFilesResponse>;

export function PickProtoFolder():Promise<main.PickProtoFolderResponse>;

export function UpdateCollection(arg1:string,arg2:main.SaveCollectionRequest):Promise<main.Collection>;

export function UpdateCollectionRequest(arg1:string,arg2:main.SaveCollectionRequestItemRequest):Promise<main.CollectionRequest>;

export function UpdateServerProfile(arg1:string,arg2:main.SaveServerProfileRequest):Promise<main.ServerProfile>;

export function ValidateProtoSources(arg1:main.ValidateProtoSourcesRequest):Promise<main.ValidateProtoSourcesResponse>;
